server:
  port: 8080

db:
  host: localhost
  port: 5432
  name: social-net
  username: postgres
  password: password

spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    generate-ddl: false
#    hibernate:
#      ddl-auto: none
  datasource:
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${db.host}:${db.port}/${db.name}"
    name: ${db.name}
    username: ${db.username}
    password: ${db.password}


